---
title: ""
output: 
  html_document:
    css: "assets/caaqs-styles.css"
---

```{r setup, include = FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = FALSE)

# Allows Rmd file to be run interactively and knit 
# without having to change the relative file locations all the time
library("here") 

# Tidyverse
library("dplyr")
library("tidyr")
library("purrr")
library("stringr")

# Mapping
library("leaflet")
library("sf")
library("geojsonio")
library("htmltools") # For HTML() function

# Functions to create popups and center map
library("envreportutils")
library("rcaaqs")

# Get css
css_caaqs_copy(folder = here("leaflet_map/"), overwrite = TRUE)

# Assign labels, colours, and cutoffs using rcaaqs ----------------------------
# Ambient labels
labels_ambient <- achievement_levels %>%
  filter(str_detect(parameter, "so2")) %>%
  select(labels, colour, units_html) %>%
  mutate(text_colour = "white") %>%
  distinct()
  
# Management labels
labels_mgmt <- management_levels %>%
  filter(str_detect(parameter, "so2")) %>%
  select(labels, colour, colour_text, units_html) %>%
  distinct() %>%
  mutate(icons = paste0("assets/marker_", colour_text, ".svg"),
         text_colour = c("white", "black", "black", "white", "white"))

  

# Load and prep data ------------------------------------

# - Stations show Management levels and have management metric data on popups
# - Airzones show Management levels and have management metric values on popups,
#   but ambient achievement levels in boxes
# - Both popups show one value box per metric

## Stations - Get CAAQs and popups ---------------------------------------
stations <- read_sf(here("out/so2_stations_mgmt.geojson")) %>%
  # Count total stations
  add_count(airzone) %>%
  filter(mgmt_level != "Insufficient Data") %>%
  left_join(labels_mgmt, by = c("mgmt_level" = "labels")) %>%
  mutate(caaqs_legend = mgmt_level) %>%
  
  # Create popups
  mutate(popup = popup_caaqs(
    ., type = "station", 
    metric_type = "SO<sub>2</sub>", 
    metrics = c("3yr", "1yr"), 
    metric_names = c("1-hour Metric", "Annual Metric"),
    units = units_html[1],
    airzone = "airzone", 
    station_name = "site", 
    station_id = "site", 
    value1 = "metric_value_mgmt_3yr", 
    value2 = "metric_value_mgmt_1yr",
    level1 = "mgmt_level"))

## Count stations
stns_n <- stations %>%
  st_set_geometry(NULL) %>%
  select(airzone, n) %>%
  distinct()

## Airzones - Get Ambient CAAQs and create popups --------------------------
# - Keep insufficient data polygons, but not popups
az <- st_read(here("./out/so2_airzones_mgmt.geojson")) %>%
  left_join(stns_n, by = "airzone") %>%
  left_join(select(labels_mgmt, labels, legend_colour = colour, icons, units_html),
            by = c("mgmt_level" = "labels")) %>%
  left_join(select(labels_ambient, labels, colour, text_colour),
            by = c("caaqs_ambient" = "labels")) %>%
  
  mutate(caaqs_legend = mgmt_level) %>%
  
  # Create Airzone tooltips
  mutate(n = replace_na(n, 0),
         tooltip = map2(airzone, n, 
                        ~HTML(paste0(.x, "<br>", .y, 
                                     " Monitoring Station", 
                                     if_else(.y == 1, "", "s"))))) %>%
  # Create popups
  mutate(popup = popup_caaqs(
    ., type = "airzone", 
    metric_type = "SO<sub>2</sub>", 
    metrics = c("3yr", "1yr"), 
    metric_names = c("1-hour Metric", "Annual Metric"),
    units = units_html[1],
    airzone = "airzone", 
    station_name = "rep_stn_id", 
    station_id = "rep_stn_id", 
    value1 = "metric_value_mgmt_3yr", 
    value2 = "metric_value_mgmt_1yr",
    level1 = "caaqs_ambient"),
    # Where insufficient data, keep the tool tip but omit the popup
    popup = if_else(caaqs_ambient == "Insufficient Data", 
                    list(NA_character_), popup))


# Start splitting metrics ----------------------

# Create palettes

pal_az <- colorFactor(palette = labels_mgmt$colour, 
                      levels = labels_mgmt$labels)


# Create icons
icon_size <- 30
markers <- icons( # file locations have to be relative (can't use here())
  iconUrl = stations$icons,
  iconWidth = icon_size, iconHeight = icon_size,
  iconAnchorX = icon_size/2, iconAnchorY = icon_size,
  shadowUrl = "assets/marker_shadow.svg",
  shadowWidth = icon_size * 0.75, shadowHeight = icon_size * 0.75,
  shadowAnchorX = 1, shadowAnchorY = icon_size * 0.75)

# Popup Options
ppo <- popupOptions(autoPanPaddingTopLeft = c(10, 10),
                    autoPanPaddingBottomRight = c(10, 400),
                    closeOnEscapeKey = TRUE, 
                    keepInView = TRUE)
```


```{r, warning=FALSE}
leaflet(width = "900px", height = "700px", options = leafletOptions(minZoom = 5)) %>% 
  addProviderTiles(providers$CartoDB) %>%
  add_bc_home_button() %>%
  # Re-centre map on popup close
  set_bc_view_on_close() %>%
  
  # Add Airzone polygons
  addPolygons(data = az,
              color = "white", weight = 2, opacity = 1, fillOpacity = 0.7,
              fillColor = ~pal_az(caaqs_legend),
              label = ~tooltip, 
              popup = ~popup,
              popupOptions = ppo) %>%
  
  # Add station markers
  addMarkers(data = stations,
             icon = markers, label = ~site, 
             popup = ~popup,
             # Stick to marker, not mouse
             labelOptions = labelOptions(sticky = FALSE, 
                                         offset = c(0, -icon_size/2))) %>%
  
  # Legend
  addLegend("bottomleft", group = "Annual",
            data = az,
            # Ensure we get all levels
            colors = rev(labels_mgmt$colour), 
            labels = rev(labels_mgmt$labels),
            opacity = 1, 
            title = htmltools::HTML(
              "<h3>SO<sub>2</sub> Management Levels</h3>"))
```
